#image:
#  repository: # TODO: Create public docker hub repository

nfs:
  path: /mnt/nfs

kafkaqueue:
  consumerBrokers: kafka.default.svc.cluster.local:9092
  producerBrokers: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.default.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.default.svc.cluster.local:9092
  username: your-username
  password: your-password

wfexecutionqueue:
  topic: wf-execution-queue

stepschedulequeue:
  topic: step-schedule-queue

hc:
  cacheTtl: 300

wfmanager:
  service:
    type: ClusterIP
    port: 10000
    portName: wf-manager-service-port

orquestador:
  service:
    type: ClusterIP
    port: 10001
    portName: orquestador-service-port

scheduler:
  service:
    type: ClusterIP
    port: 10002
    portName: sche-serv-port

taskservice:
  service:
    type: ClusterIP
    port: 10003
    portName: ts-cont-port