namespace: default

image:
  repository: # TODO: Create public docker hub repository

nfs:
  path: /mnt/nfs

kafka-queue:
  brokers: kafka-queue:30000
  username: kafka-user
  password: kafka-password

wf-execution-queue:
  topic: wf-execution-queue

step-schedule-queue:
  topic: step-schedule-queue

hc:
  cacheTtl: 300

wf-manager:
  service:
    type: ClusterIP
    port: 10000
    portName: wf-manager-service-port

orquestador:
  service:
    type: ClusterIP
    port: 10001
    portName: orquestador-service-port

scheduler:
  service:
    type: ClusterIP
    port: 10002
    portName: scheduler-service-port

task-service:
  url: # TO BE DEFINED