#image:
#  repository: # TODO: Create public docker hub repository

nfs:
  path: /mnt/nfs

kafkaqueue:
  consumerBrokers: kafka.default.svc.cluster.local:9092
  producerBrokers: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092,kafka-controller-1.kafka-controller-headless.default.svc.cluster.local:9092,kafka-controller-2.kafka-controller-headless.default.svc.cluster.local:9092
  username: your-username
  password: your-password

wfexecutionqueue:
  topic: wf-execution-queue

stepschedulequeue:
  topic: step-schedule-queue

# Esta es para lo de los errores que el scheduler le pasa al orquestador
errorqueue:
  topic: error-queue

hc:
  cacheTtl: 300

wfmanager:
  namespace: wf-manager
  service:
    name: wf-manager
    type: ClusterIP
    port: 10000
    portName: wf-manager-service-port

orquestador:
  namespace: orquestador
  service:
    name: orquestador
    type: ClusterIP
    port: 10001
    portName: orquestador-service-port

scheduler:
  namespace: scheduler
  service:
    name: scheduler
    type: ClusterIP
    port: 10002
    portName: sche-serv-port

taskservice:
  namespace: task-service # Lo uso para pegarle desde Scheduler
  service:
    name: task-service # Lo uso para pegarle desde Scheduler
    type: ClusterIP
    port: 10003
    portName: ts-cont-port