global:
  defaultStorageClass: "local-path"
architecture: standalone
auth:
  enabled: false
master:
  persistence:
    enabled: true
    size: 1Gi
replica:
  persistence:
    enabled: true
    size: 1Gi
