kraft:
  clusterId: "1"
  
sasl:
  enabledMechanisms: "plain"
  interBrokerMechanism: "plain"
  controllerMechanism: "plain"
  client:
    users: 
      - "your-username"
    passwords:
      - "your-password"
  controller:
    users:
      - "your-username"
    passwords:
      - "your-password"

broker:
  replicaCount: 3 # Esto estaba en 3
  persistence:
    size: 2Gi

controller:
  replicaCount: 3 # Esto estaba en 3
  controllerOnly: false
  persistence:
    size: 2Gi

global:
  defaultStorageClass: "local-path"

listeners:
  client:
    containerPort: 9092
    protocol: SASL_PLAINTEXT
    name: BROKER
  controller:
    containerPort: 9093
    protocol: SASL_PLAINTEXT
    name: CONTROLLER

provisioning:
  numPartitions: 3 # Esto estaba en 3
  replicationFactor: 1  
  
extraEnvVars:
  - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
    value: "true"
  - name: KAFKA_CFG_SASL_ENABLED_MECHANISMS
    value: "PLAIN"
  - name: KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL
    value: "PLAIN"
  - name: KAFKA_CFG_LISTENERS
    value: "SASL_PLAINTEXT://:9092"
  - name: KAFKA_CFG_ADVERTISED_LISTENERS
    value: "SASL_PLAINTEXT://kafka-0.kafka-headless.default.svc.cluster.local:9092"
  - name: KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND
    value: "true"