stages:
  - terraform
  - connect-to-cluster
  - set-cluster-ip
  - trigger-deployment

image: 
  name: hashicorp/terraform
  entrypoint: [""]

variables:
  TF_LOG: DEBUG

terraform-job:
  stage: terraform
  script:
    - echo $AWS_ACCESS_KEY_ID
    - echo $AWS_SECRET_ACCESS_KEY
    - echo $AWS_SESSION_TOKEN
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - export AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN"
    - cd terraform
    - terraform init
    - terraform apply -auto-approve
    
connect-to-cluster-job:
  stage: connect-to-cluster
  script:
    - echo "Connecting to the cluster"

set-cluster-ip-job:
  stage: set-cluster-ip
  script:
    - echo "Setting the cluster IP"

trigger-deployment-job:
  stage: trigger-deployment
  script:
    - echo "Triggering deployment"