stages:
  - terraform
  - connect-to-cluster
  - set-cluster-ip
  - trigger-deployment

image: 
  name: hashicorp/terraform
  entrypoint: [""]

variables:
  TF_LOG: DEBUG
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN

terraform-job:
  stage: terraform
  script:
    - cd terraform
    - terraform init
    - terraform apply -auto-approve -var "aws_access_key_id=$AWS_ACCESS_KEY_ID" -var "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" -var "aws_session_token=$AWS_SESSION_TOKEN"
    
connect-to-cluster-job:
  stage: connect-to-cluster
  script:
    - echo "Connecting to the cluster"

set-cluster-ip-job:
  stage: set-cluster-ip
  script:
    - echo "Setting the cluster IP"

trigger-deployment-job:
  stage: trigger-deployment
  script:
    - echo "Triggering deployment"