stages:
  - terraform
  - connect-to-cluster
  - set-cluster-ip
  - trigger-deployment

terraform-job:
  stage: terraform
  image: alpine:latest
  before_script:
    - apk add --no-cache bash curl
    - curl -fsSL https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip -o terraform.zip
    - unzip terraform.zip
    - mv terraform /usr/local/bin/
    - terraform version
  script:
    - export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY"
    - export AWS_SESSION_TOKEN="$AWS_SESSION_TOKEN"
    - cd terraform
    - terraform init
    - terraform apply -auto-approve



    
connect-to-cluster-job:
  stage: connect-to-cluster
  script:
    - echo "Connecting to the cluster"

set-cluster-ip-job:
  stage: set-cluster-ip
  script:
    - echo "Setting the cluster IP"

trigger-deployment-job:
  stage: trigger-deployment
  script:
    - echo "Triggering the deployment"