stages:
  - terraform
  - connect-to-cluster
  - set-cluster-ip
  - trigger-deployment

terraform-job:
  stage: terraform
  script:
    - echo "terraform init, apply and stuff"
    
connect-to-cluster-job:
  stage: connect-to-cluster
  script:
    - echo "Connecting to the cluster"

set-cluster-ip-job:
  stage: set-cluster-ip
  script:
    - echo "Setting the cluster IP"

trigger-deployment-job:
  stage: trigger-deployment
  script:
    - echo "Triggering the deployment"