stages:
  - terraform
  - connect-to-cluster
  - set-cluster-ip
  - trigger-deployment

image: 
  name: hashicorp/terraform
  entrypoint: [""]

variables:
  TF_LOG: DEBUG
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
  ENCODED_ID_ED25519: $ENCODED_ID_ED25519
  ID_ED25519_pub: $ID_ED25519_PUB

terraform-job:
  stage: terraform
  script:
    - mkdir -p ~/.ssh
    - echo "$ENCODED_ID_ED25519" | base64 -d > ~/.ssh/id_ed25519
    - echo "$ID_ED25519_pub" > ~/.ssh/id_ed25519.pub
    - chmod 600 ~/.ssh/id_ed25519
    - cd terraform
    - terraform init
    - terraform apply -auto-approve -var "aws_access_key_id=$AWS_ACCESS_KEY_ID" -var "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" -var "aws_session_token=$AWS_SESSION_TOKEN"
  only:
    - main
    
connect-to-cluster-job:
  stage: connect-to-cluster
  script:
    - echo "Connecting to the cluster"
  only:
    - main    

set-cluster-ip-job:
  stage: set-cluster-ip
  script:
    - echo "Setting the cluster IP"
  only:
    - main    

trigger-deployment-job:
  stage: trigger-deployment
  script:
    - echo "Triggering deployment"
  only:
    - main