configMapName: orquestador-config

namespace: orquestador

fullname: orquestador

container:
  port: 3000
  portName: orq-cont-port

stepschedulequeue:
  clientId: orquestador

wfexecutionqueue:
  clientId: orquestador
  groupId: orquestador

wfexecutiondb:
  host: wf-execution-db
  port: 20001
  username: user
  password: pass
  name: wf-execution
  sync: false

labels:
  app: orquestador

image:
  name: orquestador
  tag: 1.0.0 # This is the image tag (must be overridden in the ci/cd pipeline with --set image.tag=[IMAGE_TAG])

livenessProbe:
  httpGet:
    path: /ping
    port: orq-cont-port

readinessProbe:
  httpGet:
    path: /ping
    port: orq-cont-port

replicaCount: 3