apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: routes
  namespace: default
spec:
  routes:                          
  - kind: Rule
    match: PathPrefix(`/`) && !(PathPrefix(`/triggers`)  || Header(`Content-Type`, `application/grpc`) || PathPrefix(`/executions`) || PathPrefix(`/cancel-execution`) || PathPrefix(`/dashboard`) || PathPrefix(`/workflows`))
    services:                       
    - kind: Service
      name: logging-signoz-frontend
      port: 3301
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: grpc-ingress
#  namespace: workflow-manager
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  ingressClassName: nginx
#  tls: []
#  rules:
#  - http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: workflow-manager-grpc
#            port:
#              number: 9090
