configMapName: echo-agent-config

replicaCount: 2

namespace: agents

fullname: echo-agent-deployment

agentName: echo-agent
sidecarName: sidecar

agentImage:
  name: echo

sidecarImage:
  name: sidecar

ingress:
  enabled: false

agent:
  url: "http://localhost:8000/echo"
  name: "echo"
  paramNames:
    - "input"
  paramTypes:
    - "string"

schedulerToAgent:
  clientId: scheToAgentEcho
  groupId: echoAgentGroup
  topic: echoAgent # Cada Agent tiene que tener su propio tópico

labels:
  app: echo

nfs:
  path: /mnt/nfs

livenessProbe:
  httpGet:
    path: /ping
    port: 8500
readinessProbe:
  httpGet:
    path: /ping
    port: 8500
