apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.container.port }}"
  HC_CACHE_TTL: "{{ .Values.hc.cacheTtl }}"

  KAFKA_BROKERS_SSR: {{ .Values.kafkaqueue.brokers }}
  KAFKA_USERNAME_SSR: {{ .Values.kafkaqueue.username }}
  KAFKA_PASSWORD_SSR: {{ .Values.kafkaqueue.password }}
  KAFKA_CLIENT_ID_SSR_PREFIX: {{ .Values.stepschedulequeue.clientId }}
  KAFKA_TOPIC_SSR: {{ .Values.stepschedulequeue.topic }}

  KAFKA_BROKERS_WER: {{ .Values.kafkaqueue.brokers }}
  KAFKA_USERNAME_WER: {{ .Values.kafkaqueue.username }}
  KAFKA_PASSWORD_WER: {{ .Values.kafkaqueue.password }}
  KAFKA_CLIENT_ID_WER_PREFIX: {{ .Values.wfexecutionqueue.clientId }}
  KAFKA_GROUP_ID_WER: {{ .Values.wfexecutionqueue.groupId }}
  KAFKA_TOPIC_WER: {{ .Values.wfexecutionqueue.topic }}

  DB_HOST: "{{ .Values.wfexecutiondb.name }}-postgresql"
  DB_PORT: "{{ .Values.wfexecutiondb.port }}"
  DB_USERNAME: {{ .Values.wfexecutiondb.username }}
  DB_PASSWORD: {{ .Values.wfexecutiondb.password }}
  DB_NAME: {{ .Values.wfexecutiondb.name }}
  TYPEORM_SYNC: "{{ .Values.wfexecutiondb.sync }}"

  NFS_PATH: {{ .Values.nfs.path }}

  # TODO: Env vars for step response missing