apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
data:
  PORT: "{{ .Values.container.port }}"
  HC_CACHE_TTL: "{{ .Values.hc.cacheTtl }}"

  # Nombre del servicio, con el que se identifica en los logs
  SERVICE_NAME_PREFIX: {{ .Values.container.name }}

  # Esta es la URL al backend de observabilidad
  LOGGER_URL: {{ .Values.signoz.loggerUrl }}
  TRACE_URL: {{ .Values.signoz.traceUrl }}

  # Este es el principal, manda steps al scheduler
  KAFKA_BROKERS_SSR: {{ .Values.kafkaqueue.producerBrokers }}
  KAFKA_USERNAME_SSR: {{ .Values.kafkaqueue.username }}
  KAFKA_PASSWORD_SSR: {{ .Values.kafkaqueue.password }}
  KAFKA_CLIENT_ID_SSR_PREFIX: {{ .Values.stepschedulequeue.clientId }}
  KAFKA_TOPIC_SSR: {{ .Values.stepschedulequeue.topic }}

  # Recibe la info del wf-manager
  KAFKA_BROKERS_WER: {{ .Values.kafkaqueue.consumerBrokers }}
  KAFKA_USERNAME_WER: {{ .Values.kafkaqueue.username }}
  KAFKA_PASSWORD_WER: {{ .Values.kafkaqueue.password }}
  KAFKA_CLIENT_ID_WER_PREFIX: {{ .Values.wfexecutionqueue.clientId }}
  KAFKA_GROUP_ID_WER: {{ .Values.wfexecutionqueue.groupId }}
  KAFKA_TOPIC_WER: {{ .Values.wfexecutionqueue.topic }}

  # Recibe las respuestas de los agents
  KAFKA_BROKERS_SER: {{ .Values.kafkaqueue.consumerBrokers }}
  KAFKA_USERNAME_SER: {{ .Values.kafkaqueue.username }}
  KAFKA_PASSWORD_SER: {{ .Values.kafkaqueue.password }}
  KAFKA_CLIENT_ID_SER_PREFIX: {{ .Values.stepResultQueue.clientId }}
  KAFKA_GROUP_ID_SER: {{ .Values.stepResultQueue.groupId }}
  KAFKA_TOPIC_SER: {{ .Values.stepResultQueue.topic }}

  # Recibe errores del scheduler
  KAFKA_BROKERS_SEE: {{ .Values.kafkaqueue.consumerBrokers }}
  KAFKA_USERNAME_SEE: {{ .Values.kafkaqueue.username }}
  KAFKA_PASSWORD_SEE: {{ .Values.kafkaqueue.password }}
  KAFKA_CLIENT_ID_SEE_PREFIX: {{ .Values.errorschedulequeue.clientId }}
  KAFKA_GROUP_ID_SEE: {{ .Values.errorqueue.groupId }}
  KAFKA_TOPIC_SEE: {{ .Values.errorqueue.topic }}

  DB_HOST: "{{ .Values.wfexecutiondb.name }}-postgresql"
  DB_PORT: "{{ .Values.wfexecutiondb.port }}"
  DB_USERNAME: {{ .Values.wfexecutiondb.username }}
  DB_PASSWORD: {{ .Values.wfexecutiondb.password }}
  DB_NAME: {{ .Values.wfexecutiondb.name }}
  TYPEORM_SYNC: "{{ .Values.wfexecutiondb.sync }}"

  NFS_PATH: {{ .Values.nfs.path }}

  # TODO: Env vars for step response missing