namespace: default

image:
  repository: # TODO: Create public docker hub repository

kafka-queue:
  brokers: kafka-queue:30000
  username: kafka-user
  password: kafka-password

wf-execution-queue:
  topic: wf-execution-queue

hc:
  cacheTtl: 300

wf-manager:
  service:
    type: ClusterIP
    port: 10000
    portName: wf-manager-service-port