configMapName: scheduler-config

namespace: scheduler

fullname: scheduler

container:
  port: 3000
  portName: sche-cont-port

stepschedulequeue:
  clientId: scheduler
  groupId: scheduler

labels:
  app: scheduler

image:
  name: scheduler
  tag: 1.0.0 # This is the image tag (must be overridden in the ci/cd pipeline with --set image.tag=[IMAGE_TAG])

livenessProbe:
  httpGet:
    path: /ping
    port: sche-cont-port

readinessProbe:
  httpGet:
    path: /ping
    port: sche-cont-port

replicaCount: 3