configMapName: scheduler-config

namespace: scheduler

fullname: scheduler

container:
  port: 3000
  portName: sche-cont-port
  name: scheduler

stepschedulequeue:
  clientId: scheduler
  groupId: scheduler

errorschedulequeue:
  clientId: scheduleerror

labels:
  app: scheduler

image:
  name: scheduler
  tag: 1.0.0 # This is the image tag (must be overridden in the ci/cd pipeline with --set image.tag=[IMAGE_TAG])

livenessProbe:
  httpGet:
    path: /ping
    port: sche-cont-port
  initialDelaySeconds: 60  # Wait 10 seconds before the first probe
  periodSeconds: 20         # Check every 5 seconds
  failureThreshold: 3      # Allow 3 failed checks before restart

readinessProbe:
  httpGet:
    path: /ping
    port: sche-cont-port
  initialDelaySeconds: 60  # Wait 5 seconds before the first probe
  periodSeconds: 20         # Check every 3 seconds
  failureThreshold: 3      # Allow 3 failed checks before marking unready

replicaCount: 3