apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}  # Este es el nombre que va a haber que referenciar
  namespace: {{ .Values.namespace }}
data:
  PORT: {{ .Values.container.port }}
  HC_CACHE_TTL: {{ .Values.hc.cacheTtl }}

  KAFKA_BROKERS_SSR: {{ .Values.kafka-queue.brokers }}
  KAFKA_USERNAME_SSR: {{ .Values.kafka-queue.username }}
  KAFKA_PASSWORD_SSR: {{ .Values.kafka-queue.password }}
  KAFKA_CLIENT_ID_SSR_PREFIX: {{ .Values.step-schedule-queue.clientId }}
  KAFKA_GROUP_ID_SSR: {{ .Values.step-schedule-queue.groupId }}
  KAFKA_TOPIC_SSR: {{ .Values.step-schedule-queue.topic }}

  TASK_SERVICE_URL: {{ .Values.task-service.url }}