apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.fullname }}
          image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: {{ .Values.container.portName }}
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
          env:
            - name: POD_UID
              # https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: KAFKA_CLIENT_ID_SSR
              # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
              value: "{{ .Values.stepschedulequeue.clientId }}-$(POD_UID)"
            - name: KAFKA_CLIENT_ID_SEE
              # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
              value: "{{ .Values.errorschedulequeue.clientId }}-$(POD_UID)"
            - name: SERVICE_NAME
              value: "{{ .Values.container.name }}-$(POD_UID)"

