configMapName: download-agent-config

replicaCount: 2

namespace: agents

fullname: download-agent-deployment

agentName: download-agent
sidecarName: sidecar

agentImage:
  name: s3-download

sidecarImage:
  name: sidecar

agent:
  url: "http://localhost:8000/download"
  name: "download"
  paramNames:
    - "inputs"
  paramTypes:
    - "string"

schedulerToAgent:
  clientId: scheToAgentDownload
  groupId: downloadAgentGroup
  topic: downloadAgent # Cada Agent tiene que tener su propio tópico

labels:
  app: download

nfs:
  path: /mnt/nfs

livenessProbe:
  httpGet:
    path: /ping
    port: 8500
readinessProbe:
  httpGet:
    path: /ping
    port: 8500