apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.sidecarName }} # Sidecar
          image: "{{ .Values.image.repository }}{{ .Values.sidecarImage.name }}:{{ .Values.image.tag }}"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
          env:
            - name: POD_UID
              # https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: KAFKA_CLIENT_ID_SER
              # https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/
              value: "{{ .Values.stepschedulequeue.clientId }}-$(POD_UID)"
            - name: KAFKA_CLIENT_ID_STA # Scheduler to Agent
              value: "{{ .Values.schedulerToAgent.clientId }}-$(POD_UID)"
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}  # Name of the volume defined below
              mountPath: {{ .Values.volumeMounts.mountPath }}  # Mount path inside container
              readOnly: {{ .Values.volumeMounts.readOnly }}
        - name: {{ .Values.agentName }}   # Echo
          image: "{{ .Values.image.repository }}{{ .Values.agentImage.name }}:{{ .Values.image.tag }}"
          env:
            - name: AGENT_PORT
              value: "8000"
      volumes:
        - name: {{ .Values.volumes.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.persistentVolumeClaim.claimName }} 

