apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.fullname }}
          image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: {{ .Values.container.portName }}
              containerPort: {{ .Values.container.port }}
          env:
            - name: POD_UID
              # https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: REDIS_PORT
            - name: HC_CACHE_TTL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: HC_CACHE_TTL
            - name: SERVICE_NAME
              value: "{{ .Values.container.name }}-$(POD_UID)"
            - name: LOGGER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: LOGGER_URL
            - name: TRACE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMapName }}
                  key: TRACE_URL
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.livenessProbe.httpGet.port }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.readinessProbe.httpGet.port }}
