apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.portName }}
