apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingressroute
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
  routes:
    - match: "Host(`{{ .Values.ingress.host }}`)"
      kind: Rule
      services:
        - name: {{ .Values.wfmanager.service.name }}
          port: {{ .Values.wfmanager.service.port }}
