apiVersion: apps/v1
kind: Pod
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  containers:
    - name: {{ .Values.fullname }}
      image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
      ports:
        - name: {{ .Values.container.portName }}
          containerPort: {{ .Values.container.port }}
          protocol: TCP
  livenessProbe:
    {{- toYaml .Values.livenessProbe | nindent 12 }}
  readinessProbe:
    {{- toYaml .Values.readinessProbe | nindent 12 }}
  envFrom:
    - configMapRef:
        name: {{ .Values.configMapName }}
  env:
    - name: POD_UID
      valueFrom:
        fieldRef:
          fieldPath: metadata.uid
    - name: KAFKA_CLIENT_ID
      value: "$(KAFKA_CLIENT_ID_PREFIX)-$(POD_UID)"

