repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts
  - name: signoz
    url: https://charts.signoz.io

releases:
  - name: traefik
    namespace: default
    chart: traefik/traefik
    version: 24.0.0
    values:
      - installCRDs: true  

  - name: local-storage-provisioner
    namespace: local-path-storage
    chart: ./charts/local-path-provisioner
    values:
      - storageClass:
          name: "local-path"

  - name: orquestador
    chart: ./charts/orquestador
    version: 1.0.0
    namespace: orquestador
    values:
      - ./charts/orquestador/values.yaml
      - ./charts/global-values.yaml

  - name: scheduler
    chart: ./charts/scheduler
    version: 1.0.0
    namespace: scheduler
    values:
      - ./charts/scheduler/values.yaml
      - ./charts/global-values.yaml

  - name: task-service
    chart: ./charts/task-service
    version: 1.0.0
    namespace: task-service
    values:
      - ./charts/task-service/values.yaml
      - ./charts/global-values.yaml

  - name: wf-manager
    chart: ./charts/wf-manager
    version: 1.0.0
    namespace: wf-manager
    values:
      - ./charts/wf-manager/values.yaml
      - ./charts/global-values.yaml

  - name: redis-task-service
    chart: bitnami/redis
    version: 20.7.0
    namespace: task-service
    values:
      - ./charts/values-redis.yaml

  - name: redis-wf-manager
    chart: bitnami/redis
    version: 20.7.0
    namespace: wf-manager
    values:
      - ./charts/values-redis.yaml

  - name: wf-execution-db
    chart: bitnami/postgresql
    version: 16.4.7
    namespace: orquestador
    values:
      - auth:
          username: "postgres"
          password: "password"
          database: "wf-execution-db"
      - primary:
          service:
            type: ClusterIP
            ports:
              postgresql: 5432
            nodePorts:
              postgresql: 5432
          persistence:
            size: "1Gi"
      - metrics:
          enabled: false
      - global:
          defaultStorageClass: "local-path"

  - name: kafka
    chart: bitnami/kafka
    version: 31.0.0
    values:
      - ./charts/values-kafka.yaml

  - name: signoz
    chart: signoz/signoz
    namespace: default
    values:
      - ./charts/values-signoz.yaml
  
  - name: signoz-ingress
    namespace: default
    chart: ./charts/signoz-ingress

#  - name: echo-agent
#    chart: ./charts/echo
#    version: 1.0.0
#    namespace: agents
#    values:
#      - ./charts/echo/values.yaml
#      - ./charts/global-values.yaml

   
  # TODO: Add the chart for 
  #   - NFS
  #   - Each Task agent