repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: traefik
    url: https://traefik.github.io/charts
  - name: signoz
    url: https://charts.signoz.io

releases:
  - name: traefik
    namespace: default
    chart: traefik/traefik
    version: 24.0.0
    values:
      - installCRDs: true  

  - name: local-storage-provisioner
    namespace: local-path-storage
    chart: ./charts/local-path-provisioner
    values:
      - storageClass:
          name: "local-path"

  - name: orquestador
    chart: ./charts/orquestador
    version: 1.0.0
    namespace: orquestador
    values:
      - ./charts/orquestador/values.yaml
      - ./charts/global-values.yaml

  - name: scheduler
    chart: ./charts/scheduler
    version: 1.0.0
    namespace: scheduler
    values:
      - ./charts/scheduler/values.yaml
      - ./charts/global-values.yaml

  - name: task-service
    chart: ./charts/task-service
    version: 1.0.0
    namespace: task-service
    values:
      - ./charts/task-service/values.yaml
      - ./charts/global-values.yaml

  - name: wf-manager
    chart: ./charts/wf-manager
    version: 1.0.0
    namespace: wf-manager
    values:
      - ./charts/wf-manager/values.yaml
      - ./charts/global-values.yaml

  - name: redis-task-service
    chart: bitnami/redis
    version: 20.7.0
    namespace: task-service
    values:
      - architecture: standalone
      - auth:
          enabled: false
      - persistence:
          enabled: true
          size: 1Gi
      - global:
          defaultStorageClass: "local-path"

  - name: redis-wf-manager
    chart: bitnami/redis
    version: 20.7.0
    namespace: wf-manager
    values:
      - architecture: standalone
      - auth:
          enabled: false
      - persistence:
          enabled: true
          size: 1Gi
      - global:
          defaultStorageClass: "local-path"

  - name: wf-execution-db
    chart: bitnami/postgresql
    version: 16.4.7
    namespace: orquestador
    values:
      - auth:
          username: "postgres"
          password: "password"
          database: "wf-execution-db"
      - primary:
          service:
            type: ClusterIP
            ports:
              postgresql: 5432
            nodePorts:
              postgresql: 5432
          persistence:
            size: "1Gi"
      - metrics:
          enabled: false
      - global:
          defaultStorageClass: "local-path"

  - name: kafka
    chart: bitnami/kafka
    values:
      - kraft:
          clusterId: 6LQnK2nq0YlXpi4K7htzPt
      - sasl:
          client:
            users: 
              - "your-username"
            passwords:
              - "your-password"
      - broker:
          replicaCount: 2  # Increased for HA
      - controller:
          replicaCount: 2  # Increased for HA
          controllerOnly: false
      - controller:
          persistence:
            size: 2Gi
          livenessProbe:
            initialDelaySeconds: 30
          readinessProbe:
            initialDelaySeconds: 30
      - broker:
          persistence:
            size: 2Gi
          livenessProbe:
            initialDelaySeconds: 30
          readinessProbe:
            initialDelaySeconds: 30
      - listeners:
          client:
            containerPort: 9092
            protocol: PLAINTEXT
            name: BROKER
          controller:
            containerPort: 9093
            protocol: PLAINTEXT
            name: CONTROLLER
      - global:
          defaultStorageClass: "local-path"
      - extraEnvVars:
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
          - name: ALLOW_PLAINTEXT_LISTENER
            value: "yes"

#  - name: signoz
#    chart: signoz/signoz
#    namespace: default
#    version: 0.70.0
#    values:
#      - installCRDs: true
#      - global:
#          storageClass: "local-path"
#      - clickhouse:
#          persistence:
#            size: 2Gi

#  - name: echo-agent
#    chart: ./charts/echo
#    version: 1.0.0
#    namespace: agents
#    values:
#      - ./charts/echo/values.yaml
#      - ./charts/global-values.yaml

   
  # TODO: Add the chart for 
  #   - NFS
  #   - Each Task agent