releases:

  - name: traefik
    namespace: default
    chart: traefik/traefik
    version: 24.0.0  

  - name: orquestador
    chart: ./charts/orquestador
    version: 1.0.0
    values:
      - ./charts/orquestador/values.yaml
      - ./global-values.yaml

  - name: scheduler
    chart: ./charts/scheduler
    version: 1.0.0
    values:
      - ./charts/scheduler/values.yaml
      - ./global-values.yaml

  - name: task-service
    chart: ./charts/task-service
    version: 1.0.0
    values:
      - ./charts/task-service/values.yaml
      - ./global-values.yaml

  - name: wf-manager
    chart: ./charts/wf-manager
    version: 1.0.0
    values:
      - ./charts/wf-manager/values.yaml
      - ./global-values.yaml

  - name: redis-task-service
    chart: bitnami/redis
    version: 1.0.0
    namespace: task-service
    values:
      - ./values-redis.yaml

  - name: redis-wf-manager
    chart: bitnami/redis
    version: 1.0.0
    namespace: wf-manager
    values:
      - ./values-redis.yaml

  - name: wf-execution-db
    chart: bitnami/postgresql
    version: 10.0.0
    namespace: wf-execution
    values:
    - auth:
        username: "postgres"
        password: "password"
        database: "wf-execution-db"
      primary:
        service:
          type: ClusterIP
          ports:
            postgresql: 5432
          nodePorts:
            postgresql: 5432
      persistence:
        enabled: false

  - name: kafka
    chart: bitnami/kafka
    values:
      - sasl:
          client:
            users: 
              - "your-username"
            passwords:
              - "your-password"
  # TODO: Add the chart for 
  #   - NFS
  #   - Each Task agent