@ip=54.198.186.205
@base=http://{{ip}}:30000

### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./workflow.yaml

--boundary1234--

### Toggle workflow status
PUT {{base}}/workflows/Nuevo/status

### Toggle workflow status (with version)
PUT {{base}}/workflows/Nuevo/status?version=1


### Execute Workflow Request
POST {{base}}/workflows/Nuevo
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "Intentemos 75!"
  }
}


### Execute Workflow Request (with version)
POST {{base}}/workflows/Nuevo?version=1
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "Probandoo 3"
  }
}


### Get Workflow Execution
GET {{base}}/workflow-execution/4909defd8bc85ccbb4d36cbf75c0f474fa4f0bae

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/4909defd8bc85ccbb4d36cbf75c0f474fa4f0bae


### Get Specific Step
GET {{base}}/workflow-execution/06294be3f86ecaa32be8327373cda236527f72d8/steps/0


### Get all executions of a workflow
GET {{base}}/workflow-execution?workflow=Nuevo



# --------------------------- Mas complejo ---------------------------

### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./workflowMasComplejo.yaml

--boundary1234--

### Toggle workflow status
PUT {{base}}/workflows/otro/status

### Toggle workflow status (with version)
PUT {{base}}/workflows/otro/status?version=1


### Execute Workflow Request
POST {{base}}/workflows/otro
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "Primero",
    "val_echo2": "Segundo",
    "val_echo3": "Tercero"
  }
}


### Get Workflow Execution
GET {{base}}/workflow-execution/4e151cbb2d0d0527b00dd744fcb8d8c5bb94d755

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/4e151cbb2d0d0527b00dd744fcb8d8c5bb94d755







# --------------------------- Con Un From ---------------------------

### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./tripleEchoPeroNo.yaml

--boundary1234--

### Toggle workflow status
PUT {{base}}/workflows/tripleEchoPeroNo/status

### Toggle workflow status (with version)
PUT {{base}}/workflows/tripleEchoPeroNo/status?version=1


### Execute Workflow Request
POST {{base}}/workflows/tripleEchoPeroNo
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "Primero",
    "val_echo2": "Segundo"
  }
}


### Get Workflow Execution
GET {{base}}/workflow-execution/1d126efe6261619d78c2988d464db6211b414f9e

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/1d126efe6261619d78c2988d464db6211b414f9e



-------------------------- Uno con Constant ---------------------------

### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./constant.yaml

--boundary1234--


### Execute Workflow Request
POST {{base}}/workflows/constant
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "Primero",
    "val_echo3": "El tercero"
  }
}


### Get Workflow Execution
GET {{base}}/workflow-execution/1d126efe6261619d78c2988d464db6211b414f9e

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/c68ee9dbbeed6fd4895ee7b13a94ca780ee90df8



-------------------------- Uno con bash ---------------------------

### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./bash.yaml

--boundary1234--


### Execute Workflow Request
POST {{base}}/workflows/bash
Content-Type: application/json

{
  "inputArguments": {
    "val_command": "date",
    "val_echo": "Soy un echo"
  }
}

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/fa7a18309a72b26115af383fb80d814742dd0009




-------------------------- Uno con download ---------------------------

### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./download.yaml

--boundary1234--


### Execute Workflow Request
POST {{base}}/workflows/download
Content-Type: application/json

{
  "inputArguments": {
    "bucket": "microservicios-prueba-bucket",
    "region": "us-east-1",
    "file_name": "kubernetes.png"
  }
}

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/365e314636160a6e484c3a9fee5a1ca6987635d9


base64 --decode --ignore-garbage file.txt > output.png


-------------------------- Uno con internals ---------------------------



### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./internals.yaml

--boundary1234--


### Execute Workflow Request
POST {{base}}/workflows/internals123
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "AsddASDADSsdaddsdsfw"
  }
}

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/74966b04f1fc2e2dfd80200812b0110c0da90483

### Get Workflow Execution
GET {{base}}/workflow-execution/78e9aa5eb43766123ca01a82df3f3cd6267cbc85




-------------------------- Decision ---------------------------


### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./condicion.yaml

--boundary1234--


### Execute Workflow Request
POST {{base}}/workflows/condicional
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "Un Echo!",
    "laCondicion": "greater",
    "izq": "hola",
    "der": "chau"
  }
}

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/e8b03b707f8d6340f91ef3364715c2d246ec6539

### Get Workflow Execution
GET {{base}}/workflow-execution/e3fce5bef2b1a1a78e506e8587da25fced1bc9d1





-------------------------- Upload ---------------------------

### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./upload.yaml

--boundary1234--


### Execute Workflow Request
POST {{base}}/workflows/upload
Content-Type: application/json

{
  "inputArguments": {
    "bucket": "microservicios-prueba-bucket",
    "region": "us-east-1",
    "name":   "un.yaml",
    "content": "bmFtZTogIlRlc3QgUGxhbiIKZGVzY3JpcHRpb246ICJBIGRlc2NyaXB0aW9uIG9mIHRoZSB0ZXN0IHBsYW4iCnN0ZXBzOgogICAgICAgLSBuYW1lOiBob2xhCiAgICAgICAgIHRhc2s6IGVjaG8KICAgICAgICAgcGFyYW1zOgogICAgICAgICAgLSBuYW1lOiBwYXJhbTEKICAgICAgICAgICAgdHlwZTogc3RyaW5nCiAgICAgICAgICAgIHZhbHVlOiBhX2NvbXBsZXRhcl8xCiAgICAgICAgICAtIG5hbWU6IHBhcmFtMgogICAgICAgICAgICB0eXBlOiBudW1iZXIKICAgICAgICAgICAgdmFsdWU6IGFfY29tcGxldGFyXzIKICAgICAgICAgICAgY29uc3RhbnQ6IHRydWUKICAgICAgIC0gbmFtZTogamFqYWphCiAgICAgICAgIHRhc2s6IGJhc2gKICAgICAgICAgcGFyYW1zOgogICAgICAgICAgLSBuYW1lOiBwYXJhbTMKICAgICAgICAgICAgdHlwZTogYm9vbGVhbgogICAgICAgICAgICBmcm9tOiBob2xhCiAgICAgICAgICAtIG5hbWU6IHBhcmFtNAogICAgICAgICAgICB0eXBlOiBzdHJpbmdbXQogICAgICAgICAgICB2YWx1ZTogYV9jb21wbGV0YXJfMw=="
  }
}

base64 test.png > encoded.txt

### Get Workflow Execution answer
GET {{base}}/workflow-execution/answer/ff716399bbc014ca89316b5b98e5fa410a4c6d9a

### Get Workflow Execution
GET {{base}}/workflow-execution/e3fce5bef2b1a1a78e506e8587da25fced1bc9d1



