@ip=3.233.241.162
@base=http://{{ip}}:30000

### Create a Workflow
POST {{base}}/workflows
Content-Type: multipart/form-data; boundary=boundary1234

--boundary1234
Content-Disposition: form-data; name="file"; filename="workflow.yaml"
Content-Type: application/yaml

< ./workflow.yaml

--boundary1234--

### Toggle workflow status
PUT {{base}}/workflows/Nuevo/status

### Toggle workflow status (with version)
PUT {{base}}/workflows/Nuevo/status?version=1


### Execute Workflow Request
POST {{base}}/workflows/Nuevo
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "Probandooo"
  }
}


### Execute Workflow Request (with version)
POST {{base}}/workflows/Nuevo?version=1
Content-Type: application/json

{
  "inputArguments": {
    "val_echo1": "Probandoo 2"
  }
}


### Get Workflow Execution
GET {{base}}/workflow-execution/0f220f1ebeca2db2b213d9d17d989635d22759c1


### Get Specific Step
GET {{base}}/workflow-execution/0f220f1ebeca2db2b213d9d17d989635d22759c1/steps/0


### Get all executions of a workflow
GET {{base}}/workflow-execution?workflow=Nuevo


