name: internals123
description: Hace dos echos
version: "2"
steps:
  - name: echo1
    task: echo
    params:
      - name: input
        type: string
        value: val_echo1
  - name: to_upper
    task: upper
    params:
      - name: argument_to_upper
        type: string
        from: echo1
  - name: to_lower
    task: lower
    params:
      - name: argument_to_lower
        type: string
        from: echo1

