apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.wf-manager.service.port }}
      targetPort: {{ .Values.container.portName }}
      protocol: TCP
      name: {{ .Values.wf-manager.service.portName }}
  selector:
    {{- toYaml .Values.labels | nindent 4 }}
